import type { Metadata } from 'next';
// import { Geist, Geist_Mono, Orelega_One } from 'next/font/google';
import './globals.css';
import localFont from "next/font/local";

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

const orelegaOne = localFont({
  src: "Lemon-Regular.ttf",
  display: "swap",
  weight: '400',
  variable: "--font-my-font",
});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
      <body className={`${orelegaOne.variable}`}>
        {children}
      </body>
    </html>
  );
}
